# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cba980fbb1954b225fe8002bccdb4fbbf666b902781ac16740716e988f6e1d06471fd680bef35100ec84fd2734de0260823f7223667c98d9a59fd00744589c3e

test:
  secret_key_base: 47ff0a4f56a5b678e33aa2205b52ea005bdd0a8008837383e65fb1bfa32548d47c685dc32712d02a988b12a8a1e200b5bc108c53d488701ff8914f672660e446

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
